#include <cstdlib>

void controller_start()
{
	//Create database if not exists
	//if(!model_checkDB)
	//	model_createDB();
	
	//main loop
	while(1){

		//TODO MIRCO
		//NOTE: DO NOT EDIT THIS FILE
		//ask if user wants to:
		// 1 - list all the students with their current job
		// 2 - add a student
		// 3 - remove a student
		// 4 - edit a student
		// 5 - assign (and modify) tasks to students
		// 6 - quit
		
		//view_printMenu();
		//view_printPrompt();
		//c=view_xxx();

		switch(c){
			//List all the students with their current job
			case 1:			
				//TODO CARLO
				//NOTE: DO NOT EDIT THIS FILE
				
				//check if file exists
				//if exists
				//if(!model_checkDB)
				//{}
				//else
				//{}
				//
						//list all students with their current job
						//
						//while(model_isDataAvailable){
						//	view_printStudentList(model_getData("firstName"),model_getData("lastName"),model_getData("currentJob"));
						//	model_pop();
						//}
						//NOTE: Do not print anything. That is view's job
						//      Ask Mirco for adequate functions if needed.		
				//if not
						//print an error message
						//view_error("Data file not found.");
				break;
			
			case 2:
				break;
				
			case 3:
				break;
			
			case 4:
				break;
			
			case 5:
				break;
			
			
			//quit
			case 6:
				exit(0);
				break;
				
			default:
				//TODO MIRCO
				//print an error message
				//view_error("Please enter a number from 1 to 4");
				break;
		}
	
	}
		
}
		
